/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'RentalAgreementToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RentalAgreementToken__factory>
getContractFactory(name: 'RentalManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RentalManager__factory>
getContractFactory(name: 'IRentalManagerLike', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRentalManagerLike__factory>
getContractFactory(name: 'MaliciousReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MaliciousReceiver__factory>

  getContractAt(name: 'RentalAgreementToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RentalAgreementToken>
getContractAt(name: 'RentalManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RentalManager>
getContractAt(name: 'IRentalManagerLike', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRentalManagerLike>
getContractAt(name: 'MaliciousReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MaliciousReceiver>

  deployContract(name: 'RentalAgreementToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalAgreementToken>
deployContract(name: 'RentalManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalManager>
deployContract(name: 'IRentalManagerLike', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRentalManagerLike>
deployContract(name: 'MaliciousReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaliciousReceiver>

  deployContract(name: 'RentalAgreementToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalAgreementToken>
deployContract(name: 'RentalManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalManager>
deployContract(name: 'IRentalManagerLike', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRentalManagerLike>
deployContract(name: 'MaliciousReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaliciousReceiver>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  