/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace RentalManager {
      
    export type PropertyStruct = {landlord: AddressLike, title: string, location: string, monthlyRent: BigNumberish, deposit: BigNumberish, status: BigNumberish, tenant: AddressLike, depositHeld: BigNumberish, startedAt: BigNumberish, rentPaidCount: BigNumberish, imageCID: string}

    export type PropertyStructOutput = [landlord: string, title: string, location: string, monthlyRent: bigint, deposit: bigint, status: bigint, tenant: string, depositHeld: bigint, startedAt: bigint, rentPaidCount: bigint, imageCID: string] & {landlord: string, title: string, location: string, monthlyRent: bigint, deposit: bigint, status: bigint, tenant: string, depositHeld: bigint, startedAt: bigint, rentPaidCount: bigint, imageCID: string }
  
    }

  export interface RentalManagerInterface extends Interface {
    getFunction(nameOrSignature: "agreementToken" | "confirmHandover" | "endLease" | "getAllProperties" | "getProperty" | "listProperty" | "payRent" | "properties" | "propertyCount" | "rentProperty"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "HandoverConfirmed" | "LeaseEnded" | "PropertyListed" | "RentPaid" | "Rented"): EventFragment;

    encodeFunctionData(functionFragment: 'agreementToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'confirmHandover', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'endLease', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllProperties', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProperty', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'listProperty', values: [string, string, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'payRent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'properties', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'propertyCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'rentProperty', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'agreementToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmHandover', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endLease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllProperties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProperty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listProperty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'properties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rentProperty', data: BytesLike): Result;
  }

  
    export namespace HandoverConfirmedEvent {
      export type InputTuple = [id: BigNumberish, tenant: AddressLike, confirmedAt: BigNumberish];
      export type OutputTuple = [id: bigint, tenant: string, confirmedAt: bigint];
      export interface OutputObject {id: bigint, tenant: string, confirmedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LeaseEndedEvent {
      export type InputTuple = [id: BigNumberish, refundToTenant: BigNumberish, deductToLandlord: BigNumberish, endedAt: BigNumberish];
      export type OutputTuple = [id: bigint, refundToTenant: bigint, deductToLandlord: bigint, endedAt: bigint];
      export interface OutputObject {id: bigint, refundToTenant: bigint, deductToLandlord: bigint, endedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PropertyListedEvent {
      export type InputTuple = [id: BigNumberish, landlord: AddressLike, title: string, monthlyRent: BigNumberish, deposit: BigNumberish];
      export type OutputTuple = [id: bigint, landlord: string, title: string, monthlyRent: bigint, deposit: bigint];
      export interface OutputObject {id: bigint, landlord: string, title: string, monthlyRent: bigint, deposit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RentPaidEvent {
      export type InputTuple = [id: BigNumberish, tenant: AddressLike, amount: BigNumberish, paidAt: BigNumberish];
      export type OutputTuple = [id: bigint, tenant: string, amount: bigint, paidAt: bigint];
      export interface OutputObject {id: bigint, tenant: string, amount: bigint, paidAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RentedEvent {
      export type InputTuple = [id: BigNumberish, tenant: AddressLike, depositPaid: BigNumberish, startedAt: BigNumberish];
      export type OutputTuple = [id: bigint, tenant: string, depositPaid: bigint, startedAt: bigint];
      export interface OutputObject {id: bigint, tenant: string, depositPaid: bigint, startedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RentalManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): RentalManager;
    waitForDeployment(): Promise<this>;

    interface: RentalManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agreementToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    confirmHandover: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    endLease: TypedContractMethod<
      [id: BigNumberish, deductAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllProperties: TypedContractMethod<
      [],
      [RentalManager.PropertyStructOutput[]],
      'view'
    >
    

    
    getProperty: TypedContractMethod<
      [id: BigNumberish, ],
      [RentalManager.PropertyStructOutput],
      'view'
    >
    

    
    listProperty: TypedContractMethod<
      [title: string, location: string, monthlyRent: BigNumberish, deposit: BigNumberish, imageCID: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    payRent: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    properties: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, string, bigint, bigint, bigint, string] & {landlord: string, title: string, location: string, monthlyRent: bigint, deposit: bigint, status: bigint, tenant: string, depositHeld: bigint, startedAt: bigint, rentPaidCount: bigint, imageCID: string }],
      'view'
    >
    

    
    propertyCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rentProperty: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agreementToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'confirmHandover'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endLease'): TypedContractMethod<
      [id: BigNumberish, deductAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllProperties'): TypedContractMethod<
      [],
      [RentalManager.PropertyStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getProperty'): TypedContractMethod<
      [id: BigNumberish, ],
      [RentalManager.PropertyStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'listProperty'): TypedContractMethod<
      [title: string, location: string, monthlyRent: BigNumberish, deposit: BigNumberish, imageCID: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'payRent'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'properties'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, string, bigint, bigint, bigint, string] & {landlord: string, title: string, location: string, monthlyRent: bigint, deposit: bigint, status: bigint, tenant: string, depositHeld: bigint, startedAt: bigint, rentPaidCount: bigint, imageCID: string }],
      'view'
    >;
getFunction(nameOrSignature: 'propertyCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rentProperty'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'payable'
    >;

    getEvent(key: 'HandoverConfirmed'): TypedContractEvent<HandoverConfirmedEvent.InputTuple, HandoverConfirmedEvent.OutputTuple, HandoverConfirmedEvent.OutputObject>;
getEvent(key: 'LeaseEnded'): TypedContractEvent<LeaseEndedEvent.InputTuple, LeaseEndedEvent.OutputTuple, LeaseEndedEvent.OutputObject>;
getEvent(key: 'PropertyListed'): TypedContractEvent<PropertyListedEvent.InputTuple, PropertyListedEvent.OutputTuple, PropertyListedEvent.OutputObject>;
getEvent(key: 'RentPaid'): TypedContractEvent<RentPaidEvent.InputTuple, RentPaidEvent.OutputTuple, RentPaidEvent.OutputObject>;
getEvent(key: 'Rented'): TypedContractEvent<RentedEvent.InputTuple, RentedEvent.OutputTuple, RentedEvent.OutputObject>;

    filters: {
      
      'HandoverConfirmed(uint256,address,uint256)': TypedContractEvent<HandoverConfirmedEvent.InputTuple, HandoverConfirmedEvent.OutputTuple, HandoverConfirmedEvent.OutputObject>;
      HandoverConfirmed: TypedContractEvent<HandoverConfirmedEvent.InputTuple, HandoverConfirmedEvent.OutputTuple, HandoverConfirmedEvent.OutputObject>;
    

      'LeaseEnded(uint256,uint256,uint256,uint256)': TypedContractEvent<LeaseEndedEvent.InputTuple, LeaseEndedEvent.OutputTuple, LeaseEndedEvent.OutputObject>;
      LeaseEnded: TypedContractEvent<LeaseEndedEvent.InputTuple, LeaseEndedEvent.OutputTuple, LeaseEndedEvent.OutputObject>;
    

      'PropertyListed(uint256,address,string,uint256,uint256)': TypedContractEvent<PropertyListedEvent.InputTuple, PropertyListedEvent.OutputTuple, PropertyListedEvent.OutputObject>;
      PropertyListed: TypedContractEvent<PropertyListedEvent.InputTuple, PropertyListedEvent.OutputTuple, PropertyListedEvent.OutputObject>;
    

      'RentPaid(uint256,address,uint256,uint256)': TypedContractEvent<RentPaidEvent.InputTuple, RentPaidEvent.OutputTuple, RentPaidEvent.OutputObject>;
      RentPaid: TypedContractEvent<RentPaidEvent.InputTuple, RentPaidEvent.OutputTuple, RentPaidEvent.OutputObject>;
    

      'Rented(uint256,address,uint256,uint256)': TypedContractEvent<RentedEvent.InputTuple, RentedEvent.OutputTuple, RentedEvent.OutputObject>;
      Rented: TypedContractEvent<RentedEvent.InputTuple, RentedEvent.OutputTuple, RentedEvent.OutputObject>;
    
    };
  }