/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as maliciousReceiverSol from './MaliciousReceiver.sol/index.js';
export type { maliciousReceiverSol };