/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRentalManagerLike } from './IRentalManagerLike.js';
export type { MaliciousReceiver } from './MaliciousReceiver.js';