/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MaliciousReceiverInterface extends Interface {
    getFunction(nameOrSignature: "attack" | "attackRentProperty" | "manager" | "onERC721Received" | "reentryTargetId" | "reentryValue"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'attack', values?: undefined): string;
encodeFunctionData(functionFragment: 'attackRentProperty', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'manager', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'reentryTargetId', values?: undefined): string;
encodeFunctionData(functionFragment: 'reentryValue', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'attack', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attackRentProperty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'manager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reentryTargetId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reentryValue', data: BytesLike): Result;
  }

  

  export interface MaliciousReceiver extends BaseContract {
    
    connect(runner?: ContractRunner | null): MaliciousReceiver;
    waitForDeployment(): Promise<this>;

    interface: MaliciousReceiverInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attack: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    attackRentProperty: TypedContractMethod<
      [id: BigNumberish, targetIdForReentry: BigNumberish, reentryDeposit: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    manager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    reentryTargetId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    reentryValue: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attack'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'attackRentProperty'): TypedContractMethod<
      [id: BigNumberish, targetIdForReentry: BigNumberish, reentryDeposit: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'manager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reentryTargetId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'reentryValue'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }