/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRentalManagerLike__factory } from './IRentalManagerLike__factory.js';
export { MaliciousReceiver__factory } from './MaliciousReceiver__factory.js';