/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRentalManagerLike, IRentalManagerLikeInterface } from "../../../mocks/MaliciousReceiver.sol/IRentalManagerLike.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "rentProperty",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class IRentalManagerLike__factory {
    static readonly abi = _abi;
    static createInterface(): IRentalManagerLikeInterface {
      return new Interface(_abi) as IRentalManagerLikeInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRentalManagerLike {
      return new Contract(address, _abi, runner) as unknown as IRentalManagerLike;
    }
  }
  