/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { MaliciousReceiver, MaliciousReceiverInterface } from "../../../mocks/MaliciousReceiver.sol/MaliciousReceiver.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "managerAddress",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "attack",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "targetIdForReentry",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "reentryDeposit",
        "type": "uint256"
      }
    ],
    "name": "attackRentProperty",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "manager",
    "outputs": [
      {
        "internalType": "contract IRentalManagerLike",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "name": "onERC721Received",
    "outputs": [
      {
        "internalType": "bytes4",
        "name": "",
        "type": "bytes4"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "reentryTargetId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "reentryValue",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  const _bytecode = "0x60a03461007957601f6103cf38819003918201601f19168301916001600160401b0383118484101761007d5780849260209460405283398101031261007957516001600160a01b038116908190036100795760805260405161033d9081610092823960805181818160ca01528181610186015261025d0152f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe6080604081815260049182361015610021575b505050361561001f575f80fd5b005b5f925f3560e01c918263029497c11461022c57508163068f2fcf1461020f578163150b7a02146100f957508063481c6a75146100b65780639e5faafc146100935763fb523db9146100725780610012565b3461008f578160031936011261008f576020906001549051908152f35b5080fd5b503461008f578160031936011261008f5760209060ff6002541690519015158152f35b503461008f578160031936011261008f57517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b90503461020b57608036600319011261020b576001600160a01b0381358181160361020757602435818116036102075760643567ffffffffffffffff8082116102035736602383011215610203578184013590811161020357369101602401116101ff5760025460ff811661017a575b8351630a85bd0160e11b8152602090f35b90849160ff19166002557f00000000000000000000000000000000000000000000000000000000000000001691600154825491843b156101ff576024918651958694859363274daadb60e21b85528401525af180156101f3576101df575b8080610169565b6101e983916102df565b61008f57816101d8565b505051903d90823e3d90fd5b8380fd5b8580fd5b5f80fd5b8280fd5b50503461008f578160031936011261008f57602091549051908152f35b929150606036600319011261020757604435600160ff1960025416176002556024355f558060015560018060a01b037f000000000000000000000000000000000000000000000000000000000000000016903403903482116102cc57803b15610207578480926024925f9563274daadb60e21b84528035908401525af19081156102c357506102b9575080f35b61001f91506102df565b513d5f823e3d90fd5b601183634e487b7160e01b5f525260245ffd5b67ffffffffffffffff81116102f357604052565b634e487b7160e01b5f52604160045260245ffdfea26469706673582212200378c84636bfb6d32654c121bca314dd49858591f996569350163d20bf4df4da64736f6c63430008180033";

  
      type MaliciousReceiverConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MaliciousReceiverConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MaliciousReceiver__factory extends ContractFactory {
    
      constructor(...args: MaliciousReceiverConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(managerAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(managerAddress, overrides || {});
    };
    override deploy(managerAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(managerAddress, overrides || {}) as Promise<MaliciousReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MaliciousReceiver__factory {
      return super.connect(runner) as MaliciousReceiver__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MaliciousReceiverInterface {
      return new Interface(_abi) as MaliciousReceiverInterface;
    }
    
    override attach(address: string | Addressable): MaliciousReceiver {
      return super.attach(address) as MaliciousReceiver;
    }
  static connect(address: string, runner?: ContractRunner | null): MaliciousReceiver {
      return new Contract(address, _abi, runner) as unknown as MaliciousReceiver;
    }
  }

  
  